// scripts/knowledge_pages_manifest.js

export const knowledgePages = [
  // =========================
  // FX-A: FX基礎
  // =========================
  {
    id: "fx-a-root",
    title: "FXとは？",
    path: "basics/fx/what-is-fx.html",
    section: "fx",
    category: "FX基礎",
    type: "parent",
    description: "FXの基本、為替、通貨ペアなどの土台を理解する入口ページ",
  },
  {
    id: "fx-a-1",
    title: "為替とは何か",
    path: "basics/fx/what-is-exchange-rate.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "為替レートの意味と通貨交換の仕組みを理解する",
  },
  {
    id: "fx-a-2",
    title: "通貨ペアとは何か",
    path: "basics/fx/what-is-currency-pair.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "USD/JPYなど通貨ペアの読み方を理解する",
  },
  {
    id: "fx-a-3",
    title: "FXと株の違い",
    path: "basics/fx/fx-vs-stocks.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "FXと株の違いを市場構造と値動きの観点から整理する",
  },
  {
    id: "fx-a-4",
    title: "FXと暗号通貨の違い",
    path: "basics/fx/fx-vs-crypto.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "FXと暗号通貨の違いを学び方と市場構造から整理する",
  },
  {
    id: "fx-a-5",
    title: "レバレッジとは何か",
    path: "basics/fx/what-is-leverage.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "レバレッジの仕組みと注意点を理解する",
  },
  {
    id: "fx-a-6",
    title: "スプレッドとは何か",
    path: "basics/fx/what-is-spread.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "FXの実質コストであるスプレッドの基本を理解する",
  },
  {
    id: "fx-a-7",
    title: "注文の種類",
    path: "basics/fx/order-types.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "成行・指値・逆指値など注文方法の違いを整理する",
  },
  {
    id: "fx-a-8",
    title: "スワップポイントとは何か",
    path: "basics/fx/what-is-swap.html",
    section: "fx",
    category: "FX基礎",
    type: "child",
    parentId: "fx-a-root",
    description: "スワップポイントの基本と見方を理解する",
  },

  // =========================
  // FX-B: ドル円
  // =========================
  {
    id: "fx-b-root",
    title: "ドル円とは？",
    path: "basics/fx/what-is-usdjpy.html",
    section: "fx",
    category: "ドル円",
    type: "parent",
    description: "USD/JPYの基本と見方を理解する",
  },
  {
    id: "fx-b-1",
    title: "円安と円高とは何か",
    path: "basics/fx/yen-strong-weak.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "円安・円高の意味を生活と相場の両面から理解する",
  },
  {
    id: "fx-b-2",
    title: "なぜドル円は注目されるのか",
    path: "basics/fx/why-usdjpy-matters.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "日本人がドル円を優先して学ぶべき理由を整理する",
  },
  {
    id: "fx-b-3",
    title: "日銀とドル円の関係",
    path: "basics/fx/boj-and-usdjpy.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "日銀政策がドル円に与える影響を理解する",
  },
  {
    id: "fx-b-4",
    title: "米金利とドル円の関係",
    path: "basics/fx/us-rates-and-usdjpy.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "米金利の変化がドル円に影響しやすい理由を整理する",
  },
  {
    id: "fx-b-5",
    title: "ドルが強いと円が弱いの違い",
    path: "basics/fx/dollar-strong-vs-yen-weak.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "同じドル円上昇でも背景が違うことを理解する",
  },
  {
    id: "fx-b-6",
    title: "ドル円ニュースの見方",
    path: "basics/fx/how-to-read-usdjpy-news.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "ドル円関連ニュースをどう整理して読むかを学ぶ",
  },
  {
    id: "fx-b-7",
    title: "ドル円を学ぶ次の一歩",
    path: "basics/fx/next-step-after-usdjpy.html",
    section: "fx",
    category: "ドル円",
    type: "child",
    parentId: "fx-b-root",
    description: "ドル円理解の後に何を学ぶべきかを整理する",
  },

  // =========================
  // FX-C: 為替の仕組み
  // =========================
  {
    id: "fx-c-root",
    title: "なぜ為替は動くのか",
    path: "basics/fx/what-moves-fx.html",
    section: "fx",
    category: "為替の仕組み",
    type: "parent",
    description: "金利や経済指標など為替の動く理由を理解する",
  },
  {
    id: "fx-c-1",
    title: "金利と為替の関係",
    path: "basics/fx/interest-and-fx.html",
    section: "fx",
    category: "為替の仕組み",
    type: "child",
    parentId: "fx-c-root",
    description: "金利差が為替に影響しやすい理由を整理する",
  },
  {
    id: "fx-c-1-1",
    title: "利上げとは何か",
    path: "basics/fx/what-is-rate-hike.html",
    section: "fx",
    category: "為替の仕組み",
    type: "grandchild",
    parentId: "fx-c-1",
    description: "利上げの基本と為替へのつながりを理解する",
  },
  {
    id: "fx-c-1-2",
    title: "利下げとは何か",
    path: "basics/fx/what-is-rate-cut.html",
    section: "fx",
    category: "為替の仕組み",
    type: "grandchild",
    parentId: "fx-c-1",
    description: "利下げの基本と通貨の見られ方を整理する",
  },
  {
    id: "fx-c-2",
    title: "経済指標と為替の関係",
    path: "basics/fx/economic-data-and-fx.html",
    section: "fx",
    category: "為替の仕組み",
    type: "child",
    parentId: "fx-c-root",
    description: "経済指標が金利見通しを通じて為替に影響する流れを理解する",
  },
  {
    id: "fx-c-2-1",
    title: "CPIとは何か",
    path: "basics/fx/what-is-cpi.html",
    section: "fx",
    category: "為替の仕組み",
    type: "grandchild",
    parentId: "fx-c-2",
    description: "インフレ指標であるCPIの見方を初心者向けに整理する",
  },
  {
    id: "fx-c-2-2",
    title: "雇用統計とは何か",
    path: "basics/fx/what-is-nfp.html",
    section: "fx",
    category: "為替の仕組み",
    type: "grandchild",
    parentId: "fx-c-2",
    description: "米雇用統計がなぜ注目されるのかを整理する",
  },
  {
    id: "fx-c-3",
    title: "中央銀行と為替の関係",
    path: "basics/fx/central-bank-and-fx.html",
    section: "fx",
    category: "為替の仕組み",
    type: "child",
    parentId: "fx-c-root",
    description: "FRBや日銀の発言と政策が為替に影響する理由を理解する",
  },
  {
    id: "fx-c-4",
    title: "地政学リスクと為替",
    path: "basics/fx/geopolitics-and-fx.html",
    section: "fx",
    category: "為替の仕組み",
    type: "child",
    parentId: "fx-c-root",
    description: "戦争や制裁などの地政学リスクが為替に影響する流れを整理する",
  },
  {
    id: "fx-c-5",
    title: "リスクオンとリスクオフ",
    path: "basics/fx/risk-on-risk-off.html",
    section: "fx",
    category: "為替の仕組み",
    type: "child",
    parentId: "fx-c-root",
    description: "市場心理の変化が通貨選好に与える影響を理解する",
  },

  // =========================
  // FX-D: 相場構造
  // =========================
  {
    id: "fx-d-root",
    title: "相場構造を理解する",
    path: "basics/fx/market-structure.html",
    section: "fx",
    category: "相場構造",
    type: "parent",
    description: "トレンド、レンジ、高値安値など相場構造の基本を整理する",
  },
  {
    id: "fx-d-1",
    title: "トレンドとは何か",
    path: "basics/fx/what-is-trend.html",
    section: "fx",
    category: "相場構造",
    type: "child",
    parentId: "fx-d-root",
    description: "上昇トレンド・下降トレンドの基本を理解する",
  },
  {
    id: "fx-d-2",
    title: "レンジとは何か",
    path: "basics/fx/what-is-range.html",
    section: "fx",
    category: "相場構造",
    type: "child",
    parentId: "fx-d-root",
    description: "価格が一定範囲で動くレンジ相場の特徴を整理する",
  },
  {
    id: "fx-d-3",
    title: "高値と安値の見方",
    path: "basics/fx/highs-and-lows.html",
    section: "fx",
    category: "相場構造",
    type: "child",
    parentId: "fx-d-root",
    description: "相場構造を見るうえで重要な高値安値の考え方を理解する",
  },
  {
    id: "fx-d-4",
    title: "ブレイクとは何か",
    path: "basics/fx/what-is-breakout.html",
    section: "fx",
    category: "相場構造",
    type: "child",
    parentId: "fx-d-root",
    description: "価格帯の突破が相場に与える意味を整理する",
  },

  // =========================
  // FX-E: FXニュース
  // =========================
  {
    id: "fx-e-root",
    title: "FXニュースの読み方",
    path: "basics/fx/how-to-read-fx-news.html",
    section: "fx",
    category: "FXニュース",
    type: "parent",
    description: "ニュースをどう解釈するかを学ぶ",
  },
  {
    id: "fx-e-1",
    title: "見出しで終わらせない読み方",
    path: "basics/fx/headline-vs-context.html",
    section: "fx",
    category: "FXニュース",
    type: "child",
    parentId: "fx-e-root",
    description: "見出しだけで判断しないための基本手順を整理する",
  },
  {
    id: "fx-e-2",
    title: "織り込みとは何か",
    path: "basics/fx/what-is-priced-in.html",
    section: "fx",
    category: "FXニュース",
    type: "child",
    parentId: "fx-e-root",
    description: "市場が事前期待を価格に反映する考え方を理解する",
  },
  {
    id: "fx-e-3",
    title: "強い数字でも上がらない理由",
    path: "basics/fx/why-strong-data-does-not-always-rise.html",
    section: "fx",
    category: "FXニュース",
    type: "child",
    parentId: "fx-e-root",
    description: "数字の強弱と市場反応が一致しない理由を整理する",
  },

  // =========================
  // CRYPTO-A: 暗号資産基礎
  // =========================
  {
    id: "crypto-a-root",
    title: "暗号通貨とは？",
    path: "basics/crypto/what-is-crypto.html",
    section: "crypto",
    category: "暗号資産基礎",
    type: "parent",
    description: "暗号資産の基本と仕組みを理解する",
  },
  {
    id: "crypto-a-1",
    title: "ビットコインとは何か",
    path: "basics/crypto/what-is-bitcoin.html",
    section: "crypto",
    category: "暗号資産基礎",
    type: "child",
    parentId: "crypto-a-root",
    description: "BTCの役割と価値の考え方を理解する",
  },
  {
    id: "crypto-a-2",
    title: "イーサリアムとは何か",
    path: "basics/crypto/what-is-ethereum.html",
    section: "crypto",
    category: "暗号資産基礎",
    type: "child",
    parentId: "crypto-a-root",
    description: "ETHの役割とビットコインとの違いを整理する",
  },
  {
    id: "crypto-a-3",
    title: "アルトコインとは何か",
    path: "basics/crypto/what-is-altcoin.html",
    section: "crypto",
    category: "暗号資産基礎",
    type: "child",
    parentId: "crypto-a-root",
    description: "アルトコインの意味と市場での位置づけを理解する",
  },
  {
    id: "crypto-a-4",
    title: "ステーブルコインとは何か",
    path: "basics/crypto/what-is-stablecoin.html",
    section: "crypto",
    category: "暗号資産基礎",
    type: "child",
    parentId: "crypto-a-root",
    description: "価格安定型トークンの役割を整理する",
  },

  // =========================
  // CRYPTO-B: ブロックチェーン
  // =========================
  {
    id: "crypto-b-root",
    title: "ブロックチェーンとは？",
    path: "basics/crypto/what-is-blockchain.html",
    section: "crypto",
    category: "ブロックチェーン",
    type: "parent",
    description: "ブロックチェーンの基本構造を理解する",
  },
  {
    id: "crypto-b-1",
    title: "分散型とは何か",
    path: "basics/crypto/what-is-decentralization.html",
    section: "crypto",
    category: "ブロックチェーン",
    type: "child",
    parentId: "crypto-b-root",
    description: "分散管理の考え方を初心者向けに整理する",
  },
  {
    id: "crypto-b-2",
    title: "ノードとは何か",
    path: "basics/crypto/what-is-node.html",
    section: "crypto",
    category: "ブロックチェーン",
    type: "child",
    parentId: "crypto-b-root",
    description: "ノードの役割とネットワーク維持の仕組みを理解する",
  },
  {
    id: "crypto-b-3",
    title: "ガス代とは何か",
    path: "basics/crypto/what-is-gas-fee.html",
    section: "crypto",
    category: "ブロックチェーン",
    type: "child",
    parentId: "crypto-b-root",
    description: "ガス代が発生する理由と見方を整理する",
  },
  {
    id: "crypto-b-4",
    title: "L1とL2の違い",
    path: "basics/crypto/l1-vs-l2.html",
    section: "crypto",
    category: "ブロックチェーン",
    type: "child",
    parentId: "crypto-b-root",
    description: "レイヤー1とレイヤー2の違いを整理する",
  },

  // =========================
  // CRYPTO-C: 主要銘柄
  // =========================
  {
    id: "crypto-c-root",
    title: "主要銘柄を理解する",
    path: "basics/crypto/major-crypto-assets.html",
    section: "crypto",
    category: "主要銘柄",
    type: "parent",
    description: "主要な暗号資産を役割ごとに整理して理解する",
  },
  {
    id: "crypto-c-1",
    title: "BTCとETHの違い",
    path: "basics/crypto/btc-vs-eth.html",
    section: "crypto",
    category: "主要銘柄",
    type: "child",
    parentId: "crypto-c-root",
    description: "2大銘柄の役割の違いを整理する",
  },
  {
    id: "crypto-c-2",
    title: "時価総額を見る意味",
    path: "basics/crypto/why-market-cap-matters.html",
    section: "crypto",
    category: "主要銘柄",
    type: "child",
    parentId: "crypto-c-root",
    description: "時価総額が市場理解の土台になる理由を学ぶ",
  },
  {
    id: "crypto-c-3",
    title: "流動性とは何か",
    path: "basics/crypto/what-is-liquidity.html",
    section: "crypto",
    category: "主要銘柄",
    type: "child",
    parentId: "crypto-c-root",
    description: "流動性の高低が価格形成に与える影響を整理する",
  },

  // =========================
  // CRYPTO-D: 市場テーマ
  // =========================
  {
    id: "crypto-d-root",
    title: "市場テーマとは何か",
    path: "basics/crypto/what-is-market-theme.html",
    section: "crypto",
    category: "市場テーマ",
    type: "parent",
    description: "AI・DeFiなどテーマでの資金の動きを理解する",
  },
  {
    id: "crypto-d-1",
    title: "AIとは何か",
    path: "basics/crypto/what-is-ai-theme.html",
    section: "crypto",
    category: "市場テーマ",
    type: "child",
    parentId: "crypto-d-root",
    description: "AIテーマが暗号資産市場で注目される理由を整理する",
  },
  {
    id: "crypto-d-2",
    title: "DeFiとは何か",
    path: "basics/crypto/what-is-defi.html",
    section: "crypto",
    category: "市場テーマ",
    type: "child",
    parentId: "crypto-d-root",
    description: "分散型金融の基本と仕組み",
  },
  {
    id: "crypto-d-3",
    title: "NFTとは何か",
    path: "basics/crypto/what-is-nft.html",
    section: "crypto",
    category: "市場テーマ",
    type: "child",
    parentId: "crypto-d-root",
    description: "NFTの基本と市場テーマとしての見方を整理する",
  },
  {
    id: "crypto-d-4",
    title: "L2テーマとは何か",
    path: "basics/crypto/what-is-l2-theme.html",
    section: "crypto",
    category: "市場テーマ",
    type: "child",
    parentId: "crypto-d-root",
    description: "L2関連銘柄がテーマとして意識される理由を理解する",
  },
  {
    id: "crypto-d-2-1",
    title: "TVLとは何か",
    path: "basics/crypto/what-is-tvl.html",
    section: "crypto",
    category: "市場テーマ",
    type: "grandchild",
    parentId: "crypto-d-2",
    description: "DeFi分析でよく使われるTVLの意味を整理する",
  },
  {
    id: "crypto-d-2-2",
    title: "DEXとは何か",
    path: "basics/crypto/what-is-dex.html",
    section: "crypto",
    category: "市場テーマ",
    type: "grandchild",
    parentId: "crypto-d-2",
    description: "分散型取引所の基本構造と見方を理解する",
  },

  // =========================
  // CRYPTO-E: プロジェクト分析
  // =========================
  {
    id: "crypto-e-root",
    title: "プロジェクト分析の基本",
    path: "basics/crypto/how-to-analyze-projects.html",
    section: "crypto",
    category: "プロジェクト分析",
    type: "parent",
    description: "暗号資産プロジェクトを何で比較するかの基本を整理する",
  },
  {
    id: "crypto-e-1",
    title: "ユースケースの見方",
    path: "basics/crypto/how-to-read-use-case.html",
    section: "crypto",
    category: "プロジェクト分析",
    type: "child",
    parentId: "crypto-e-root",
    description: "そのプロジェクトが何を解決しようとしているかを見る",
  },
  {
    id: "crypto-e-2",
    title: "トークノミクスとは何か",
    path: "basics/crypto/what-is-tokenomics.html",
    section: "crypto",
    category: "プロジェクト分析",
    type: "child",
    parentId: "crypto-e-root",
    description: "供給設計と価値の見られ方の関係を理解する",
  },
  {
    id: "crypto-e-3",
    title: "コミュニティと採用の見方",
    path: "basics/crypto/community-and-adoption.html",
    section: "crypto",
    category: "プロジェクト分析",
    type: "child",
    parentId: "crypto-e-root",
    description: "利用者やコミュニティの広がりを見る基本を整理する",
  },

  // =========================
  // CRYPTO-F: 暗号資産ニュース
  // =========================
  {
    id: "crypto-f-root",
    title: "暗号資産ニュースの読み方",
    path: "basics/crypto/how-to-read-crypto-news.html",
    section: "crypto",
    category: "暗号資産ニュース",
    type: "parent",
    description: "暗号資産ニュースをテーマ・地合い・中身で読む基本を整理する",
  },
  {
    id: "crypto-f-1",
    title: "テーマニュースの読み方",
    path: "basics/crypto/how-to-read-theme-news.html",
    section: "crypto",
    category: "暗号資産ニュース",
    type: "child",
    parentId: "crypto-f-root",
    description: "市場テーマに関するニュースをどう解釈するかを学ぶ",
  },
  {
    id: "crypto-f-2",
    title: "規制ニュースの読み方",
    path: "basics/crypto/how-to-read-regulation-news.html",
    section: "crypto",
    category: "暗号資産ニュース",
    type: "child",
    parentId: "crypto-f-root",
    description: "規制や制度変更が市場に与える影響を整理する",
  },

  // =========================
  // COMMON
  // =========================
  {
    id: "common-1",
    title: "相場ニュースの読み方",
    path: "basics/common/how-to-read-news.html",
    section: "common",
    category: "共通知識",
    type: "parent",
    description: "ニュースの解釈方法を学ぶ",
  },
  {
    id: "common-2",
    title: "事実と解釈の違い",
    path: "basics/common/fact-vs-interpretation.html",
    section: "common",
    category: "共通知識",
    type: "child",
    parentId: "common-1",
    description: "事実と解釈を分けて読む習慣を身につける",
  },
  {
    id: "common-3",
    title: "FXと暗号通貨の違い",
    path: "basics/common/fx-vs-crypto-overview.html",
    section: "common",
    category: "共通知識",
    type: "parent",
    description: "FXと暗号通貨の違いを、値動き・仕組み・学び方の違いから整理する",
  },
  {
    id: "common-4",
    title: "時間軸の考え方",
    path: "basics/common/timeframe-thinking.html",
    section: "common",
    category: "共通知識",
    type: "parent",
    description: "短期・中期・長期で情報の意味が変わることを理解する",
  },
  {
    id: "common-5",
    title: "リスク管理の基本",
    path: "basics/common/risk-management.html",
    section: "common",
    category: "共通知識",
    type: "parent",
    description: "資金・情報・判断の3つの観点からリスク管理を整理する",
  },
  {
    id: "common-6",
    title: "情報源の使い分け",
    path: "basics/common/how-to-use-information-sources.html",
    section: "common",
    category: "共通知識",
    type: "parent",
    description: "一次情報・ニュース・SNSの使い分け方を整理する",
  },

  // =========================
  // GUIDES
  // =========================
  {
    id: "guide-1",
    title: "FX口座の選び方",
    path: "basics/guides/best-fx-brokers.html",
    section: "guide",
    category: "実用ガイド",
    type: "parent",
    description: "口座比較と選び方",
  },
  {
    id: "guide-2",
    title: "暗号通貨取引所の選び方",
    path: "basics/guides/best-crypto-exchanges.html",
    section: "guide",
    category: "実用ガイド",
    type: "parent",
    description: "暗号資産の取引所を比較するポイント",
  },
  {
    id: "guide-3",
    title: "ニュース学習の習慣化",
    path: "basics/guides/how-to-build-news-routine.html",
    section: "guide",
    category: "実用ガイド",
    type: "parent",
    description: "日々のニュース学習を継続するための習慣づくりを整理する",
  },
  {
    id: "guide-4",
    title: "ウォレットの基本",
    path: "basics/guides/what-is-wallet.html",
    section: "guide",
    category: "実用ガイド",
    type: "parent",
    description: "暗号資産ウォレットの基本と種類を理解する",
  },
  {
    id: "guide-5",
    title: "学習ロードマップ",
    path: "basics/guides/study-roadmap.html",
    section: "guide",
    category: "実用ガイド",
    type: "parent",
    description: "初心者が何から学べばよいかを順番で整理する",
  },
];
